import { Propiedad } from "../types/Propiedad";

export const propiedades: Propiedad[] = [
  {
    id: "CAP7634787",
    titulo: "Scalabrini Ortiz al 300",
    operacion: "venta",
    tipo: "Departamento",
    precio: {
      moneda: "USD",
      valor: 160000,
    },
    ubicacion: {
      calle: "Scalabrini Ortiz",
      altura: 300,
      barrio: "Villa Crespo",
      ciudad: "CABA",
      provincia: "Buenos Aires",
      pais: "Argentina",
    },
    estado: {
      condicion: "Excelente",
      antiguedad: "A estrenar",
      situacion: "Vacía",
      disposicion: "Frente",
      orientacion: null,
      credito: "Sin especificar",
    },
    caracteristicas: {
      ambientes: 2,
      dormitorios: 1,
      banos: 2,
      toilettes: 1,
      cocheras: 0,
      plantas: 1,
    },
    superficies: {
      cubierta: 44,
      semicubierta: 7,
      descubierta: 0,
      total: 51,
    },
    descripcion:
      "Departamento de dos ambientes con balcón. Hall de recepción con espacio de guardado y toilette. Cocina integrada con amoblamientos completos e isla divisora. Living comedor con salida a balcón. Dormitorio en suite con vestidor y baño completo. Calefacción por losa radiante y preinstalación de aire acondicionado en living y dormitorio. Edificio de 12 pisos con local comercial en planta baja.",
    servicios: [
      "Agua caliente central",
      "Losa radiante",
      "Preinstalación de aire acondicionado",
    ],
    ambientes: [
      "Balcón",
      "Cocina",
      "Living Comedor",
      "Palier",
      "Toilette",
      "Vestidor",
      "Hall",
      "Cocina Americana",
    ],
    amenities: ["SUM", "Parrilla", "Solarium", "Bicicletero", "Laundry"],
    imagenes: [
      "https://static.tokkobroker.com/w_pics/7634787_21489215555141158144708660658549155972110207042413018522152500754390580486695.jpg",
      "https://static.tokkobroker.com/w_pics/7634787_30636389341290431658299053755622475240500487300422630814931823988807999626642.jpg",
      "https://static.tokkobroker.com/w_pics/7634787_31802355378138821996150991683656344273736879042059899572057708492349696923638.jpg",
    ],
    observaciones_legales: [
      "Las medidas son aproximadas",
      "Los precios son orientativos y no contractuales",
    ],
  },
  {
    id: "CBU12207-AP2165946",
    titulo: "Ciudad de La Paz 2781",
    operacion: "venta",
    tipo: "Departamento",
    precio: {
      moneda: "USD",
      valor: 340000,
    },
    ubicacion: {
      calle: "Ciudad de La Paz",
      altura: 2781,
      barrio: "Belgrano",
      ciudad: "CABA",
      provincia: "Buenos Aires",
      pais: "Argentina",
      referencias:
        "Entre Pedro I. Rivera y Manuel Ugarte, a metros de estación Congreso de Tucumán",
    },
    estado: {
      condicion: "Excelente",
      antiguedad: "A estrenar",
      situacion: "Vacía",
      disposicion: "Frente",
      orientacion: "Noreste",
      credito: "Sin especificar",
    },
    caracteristicas: {
      ambientes: 3,
      dormitorios: 2,
      banos: 2,
      toilettes: 0,
      cocheras: 0,
      plantas: 1,
    },
    ambientes: [
      "Balcón",
      "Cocina",
      "Living Comedor",
      "Cocina Americana",
      "Terraza",
      "Balcón Terraza",
    ],
    superficies: {
      cubierta: 73,
      semicubierta: 0,
      descubierta: 50,
      total: 123,
    },
    descripcion:
      "Departamento premium de 3 ambientes al frente con balcón terraza. Unidad ubicada en piso 12 con vista panorámica en esquina. Estar comedor con gran altura de techos, pisos de madera y salida a amplio balcón terraza con parrilla propia. Cocina abierta al living comedor con amoblamientos completos.",
    servicios: [
      "Electricidad",
      "Agua caliente central",
      "Preinstalación de aire acondicionado",
    ],
    amenities: [
      "Solarium",
      "Piscina",
      "SUM",
      "Laundry",
      "Gimnasio",
      "Parrilla",
    ],
    imagenes: [],
    observaciones_legales: [
      "Las imágenes son ilustrativas",
      "Las medidas son aproximadas",
    ],
  },
  {
    id: "SANBENITO-LAGUNA-001",
    titulo: "Barrio San Benito a la laguna",
    operacion: "venta",
    tipo: "Casa",
    precio: {
      moneda: "USD",
      valor: 720000,
    },
    ubicacion: {
      calle: "Barrio San Benito",
      altura: null,
      barrio: "San Benito",
      ciudad: "Maschwitz",
      provincia: "Buenos Aires",
      pais: "Argentina",
      referencias: "Lote a la laguna con muelle propio",
    },
    estado: {
      condicion: "Excelente",
      antiguedad: "A estrenar",
      situacion: "Disponible",
      disposicion: "Lote a la laguna",
      orientacion: "Este",
      credito: "Sin especificar",
    },
    caracteristicas: {
      ambientes: 6,
      dormitorios: 4,
      banos: 5,
      toilettes: 1,
      cocheras: 2,
      plantas: 2,
    },
    superficies: {
      cubierta: 270,
      semicubierta: 92,
      descubierta: 708,
      total: 1070,
    },
    descripcion:
      "Casa premium sobre lote a la laguna con vista abierta. En planta baja living comedor con hogar, cocina con isla, toilette, lavadero y dependencia. Galería con parrilla y pileta. En planta alta master suite con vestidor y tres dormitorios en suite.",
    servicios: [
      "Gas natural",
      "Energía trifásica",
      "Internet",
      "Agua caliente central",
    ],
    ambientes: [
      "Living comedor",
      "Terraza",
      "Toilette",
      "Jardín",
      "Vestidor",
      "Lavadero",
      "Escritorio",
      "Cocina",
      "Baño de servicio",
      "Galería",
    ],
    amenities: [
      "Laguna",
      "Muelle",
      "Pileta",
      "Parrilla",
      "Barrio privado",
      "Seguridad",
    ],
    imagenes: [],
    observaciones_legales: ["Las medidas son aproximadas"],
  },
];
